name: Build Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/#25/mlflow

jobs:
  # Testing
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
        activate-environment: mle-dev
        auto-update-conda: true
        python-version: 3.10.15
        environment-file: env.yml
        auto-activate-base: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Testing module imports and unit tests
      run: |
        pip install pytest
        pytest


  # Build Job
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        shell: bash -el {0}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
        activate-environment: mle-dev
        auto-update-conda: true
        python-version: 3.10.15
        environment-file: env.yml
        auto-activate-base: false

    - name: Install tree CLI tool
      run: sudo apt-get install tree

    - name: Display directory tree before build
      run: tree

    - name: Build the Python package
      run: |
        pip install wheel setuptools build
        python -m build

    - name: Installing build package using sphinx
      run: |
        pip install sphinx sphinx-rtd-theme
        pip install make
        cd docs
        make clean html
        cd ..

    - name: Display directory tree after build
      run: tree

    - name: Move scripts and html files to dist
      run: |
        mv scripts dist
        mv docs/_build/html/* dist

    - name: Display directory tree after build
      run: tree

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-build
        path: dist/
# Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package-build
        path: ./artifact

    - name: Install the Python package
      run: |
        ls -R
        pip install mlflow
        pip install ./artifact/*.whl


    - name: Display tree
      run: |
        tree
        pwd
        ls

    # Ensure the scripts directory is in the PATH and is executable
    - name: Make scripts executable and export PATH
      run: |
        chmod +x artifact/scripts/*.py  # Make all Python scripts in the scripts directory executable
        export PATH="$PATH:$(pwd)/artifact/scripts"  # Add scripts directory to PATH

    - name: Running MLFlow
      run: |
        cd artifact/scripts
        python main.py

    # # Running ingest_data script with -h
    # - name: Running ingest_data script with -h
    #   run: |
    #     python artifact/scripts/ingest_data.py -h

    # # Running ingest_data script without arguments
    # - name: Running ingest_data script without arguments
    #   run: |
    #     python artifact/scripts/ingest_data.py --data_output_folder ./data --log-level INFO --log-path ./logs/ingest_data.log

    # # Running train script with -h
    # - name: Running train script with -h
    #   run: |
    #     python artifact/scripts/train.py -h

    # # Running train script without arguments
    # - name: Running train script without arguments
    #   run: |
    #     python artifact/scripts/train.py --dataset_folder ./data --model_output_folder ./models --log-level INFO --log-path ./logs/train.log

    # # Running score script with -h
    # - name: Running score script with -h
    #   run: |
    #     python artifact/scripts/score.py -h

    # # Running score script without arguments
    # - name: Running score script without arguments
    #   run: |
    #     python artifact/scripts/score.py --model_folder ./models --dataset_folder ./data --output_folder ./results --log-level INFO --log-path ./logs/score.log

